#!/bin/bash

################################################################################
#                                                                              #
#                                 {o,o}                                        #
#                                 |)__)                                        #
#                                 -"-"-                                        #
#                                                                              #
################################################################################
#
#Exampler preBuild script.This script is used on all enviorments.
#
##############################---FUNCTIONS---###################################
#This runs bower, npm and gulp in the projectbuilder container.
# For more details look it up:
# https://registry.hub.docker.com/u/kendu/projectbuilder/
function provision() {
    docker run \
        --rm \
        -v $(pwd):/opt/web \
        -w /opt/web  \
        kendu/projectbuilder \
        bash -c "echo 'INFO: Starting integration.'
if [ -e composer.json ]
then
echo 'INFO: Running composer'
composer install
fi

if [ -e package.json ]
then
echo 'INFO: Running npm'
npm install --no-bin-links
npm rebuild node-sass
fi

if [ -e bower.json ]
then
echo 'INFO: Running bower'
bower install --allow-root
fi

if [ -e Gruntfile.js ]
then
    echo 'INFO: Runing grunt'
    grunt
fi

if [ -e gulpfile.js ]
then
echo 'INFO: Running gulp'
gulp build
fi

echo 'INFO: Finished'
exit 0 "
}

################################################################################

###############################---EXECUTION---##################################

#Provision
provision

################################################################################
