wp:
  image: kendu/wordpress
  environment:
    - VIRTUAL_HOST=wp-repo.local
    - WORDPRESS_DB_HOST=mysql
    - WORDPRESS_DB_USER=wp_user
    - WORDPRESS_DB_PASSWORD=secretPassowrd
    - WORDPRESS_DB_NAME=wp_database
  volumes:
      - ./wp:/var/www/html/wp-content
  hostname:   wp-repo.local

builder:
  image:    kendu/projectbuilder
  volumes:
    - .:/opt/web
  working_dir: /opt/web
